### ISSUE TITLE
是否可以增加对 dark: 的支持 

### ISSUE THREAD

**Issue by cococa** [northernCold/unplugin-tailwindcss-shortener#1]

**Comment by northernCold** [comment]
![image](https://github.com/user-attachments/assets/53f8ca26-9960-4d60-9fae-5ded92680a5f)

我测试了这几种 darkMode 配置以及默认配置，类名压缩后都还是正常的。你的配置是什么？

**Comment by cococa** [comment]
sorry，我的锅，dark: 后面的自定义class丢失了，所以导致名字没改，感谢！
